### PR TITLE
Override SchemaStatements#foreign_keys

### PR DESCRIPTION
**Pull request by keithdoggett**
Override the `foreign_keys` method in `SchemaStatements` to help speed up the `disable_referential_integrity` method (https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/master/lib/active_record/connection_adapters/cockroachdb/referential_integrity.rb) which is causing slow tests.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm! i just re-ran CI to see if that helps

**Comment by keithdoggett** [comment]
Looks like it hit a foreign key issue again. Not sure exactly what is causing that. Maybe the order the foreign keys are added back in `disable_referential_integrity`?

**Comment by rafiss** [comment]
Hm, that's a good theory...It does seem like `add_foreign_keys` appeared in the error trace

**Comment by rafiss** [comment]
@keithdoggett i think it still is worth getting this in

**Comment by keithdoggett** [comment]
Sounds good I'll merge once the CI finishes

**Pull request merged**
